name: draw
version: 0.4.4
description: 'A fully-featured Reddit API wrapper for Dart, inspired by PRAW.'
homepage: 'https://github.com/draw-dev/DRAW'
authors:
  - Ben Konyi <bkonyi@google.com>
  - Kartik Chopra

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  collection: '^1.14.3'
  color:
    git:
      url: git://github.com/draw-dev/Color.git
      ref: 1557edd4e348926597e4139a2b98f11755eba031
  http: '^0.11.3+14'
  ini:
    git:
      url: git://github.com/draw-dev/dart-ini.git
      ref: e125c4bd1f62ffa36fc69a5b7f098dc83c11fa68
  logging: '^0.11.3+1'
  oauth2: '^1.1.0'
  path: '^1.4.2'
  quiver: '>=2.0.0 <3.0.0'

dev_dependencies:
  mockito: '^3.0.0'
  reply: '^0.1.2-dev'
  test: '^1.3.0'

# TODO(bkonyi): remove these.
# Temporary until package SDK restrictions are updated.
dependency_overrides:
  reply: '0.1.2-dev'
