name: draw
version: 0.1.3
description: 'A Reddit API wrapper for Dart, inspired by PRAW.'
homepage: 'https://github.com/draw-dev/DRAW'
authors:
  - Ben Konyi <bkonyi@google.com>
  - Kartik Chopra

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  collection: '^1.14.3'
  http: '^0.11.3+14'
  ini: '^1.1.0'
  oauth2: '^1.1.0'
  path: '^1.4.2'
  quiver: '>=0.26.2 <0.29.0'

dev_dependencies:
  mockito: '^2.2.1'
  reply: '^0.1.2-dev'
  test: '^0.12.5'
